/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Descriptions"
 * 	found in "asn1/S1AP-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -S skeletons -D asn1c`
 */

#ifndef	_InitiatingMessage_H_
#define	_InitiatingMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProcedureCode.h"
#include "Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "HandoverRequired.h"
#include "HandoverCommand.h"
#include "HandoverPreparationFailure.h"
#include "HandoverRequest.h"
#include "HandoverRequestAcknowledge.h"
#include "HandoverFailure.h"
#include "PathSwitchRequest.h"
#include "PathSwitchRequestAcknowledge.h"
#include "PathSwitchRequestFailure.h"
#include "E-RABSetupRequest.h"
#include "E-RABSetupResponse.h"
#include "E-RABModifyRequest.h"
#include "E-RABModifyResponse.h"
#include "E-RABReleaseCommand.h"
#include "E-RABReleaseResponse.h"
#include "InitialContextSetupRequest.h"
#include "InitialContextSetupResponse.h"
#include "InitialContextSetupFailure.h"
#include "HandoverCancel.h"
#include "HandoverCancelAcknowledge.h"
#include "Reset.h"
#include "ResetAcknowledge.h"
#include "S1SetupRequest.h"
#include "S1SetupResponse.h"
#include "S1SetupFailure.h"
#include "UEContextModificationRequest.h"
#include "UEContextModificationResponse.h"
#include "UEContextModificationFailure.h"
#include "UEContextReleaseCommand.h"
#include "UEContextReleaseComplete.h"
#include "ENBConfigurationUpdate.h"
#include "ENBConfigurationUpdateAcknowledge.h"
#include "ENBConfigurationUpdateFailure.h"
#include "MMEConfigurationUpdate.h"
#include "MMEConfigurationUpdateAcknowledge.h"
#include "MMEConfigurationUpdateFailure.h"
#include "WriteReplaceWarningRequest.h"
#include "WriteReplaceWarningResponse.h"
#include "HandoverNotify.h"
#include "E-RABReleaseIndication.h"
#include "Paging.h"
#include "DownlinkNASTransport.h"
#include "InitialUEMessage.h"
#include "UplinkNASTransport.h"
#include "ErrorIndication.h"
#include "NASNonDeliveryIndication.h"
#include "UEContextReleaseRequest.h"
#include "DownlinkS1cdma2000tunneling.h"
#include "UplinkS1cdma2000tunneling.h"
#include "UECapabilityInfoIndication.h"
#include "ENBStatusTransfer.h"
#include "MMEStatusTransfer.h"
#include "DeactivateTrace.h"
#include "TraceStart.h"
#include "TraceFailureIndication.h"
#include "CellTrafficTrace.h"
#include "LocationReportingControl.h"
#include "LocationReportingFailureIndication.h"
#include "LocationReport.h"
#include "OverloadStart.h"
#include "OverloadStop.h"
#include "ENBDirectInformationTransfer.h"
#include "MMEDirectInformationTransfer.h"
#include "ENBConfigurationTransfer.h"
#include "MMEConfigurationTransfer.h"
#include "PrivateMessage.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InitiatingMessage__value_PR {
	InitiatingMessage__value_PR_NOTHING,	/* No components present */
	InitiatingMessage__value_PR_HandoverRequired,
	InitiatingMessage__value_PR_HandoverRequest,
	InitiatingMessage__value_PR_PathSwitchRequest,
	InitiatingMessage__value_PR_E_RABSetupRequest,
	InitiatingMessage__value_PR_E_RABModifyRequest,
	InitiatingMessage__value_PR_E_RABReleaseCommand,
	InitiatingMessage__value_PR_InitialContextSetupRequest,
	InitiatingMessage__value_PR_HandoverCancel,
	InitiatingMessage__value_PR_Reset,
	InitiatingMessage__value_PR_S1SetupRequest,
	InitiatingMessage__value_PR_UEContextModificationRequest,
	InitiatingMessage__value_PR_UEContextReleaseCommand,
	InitiatingMessage__value_PR_ENBConfigurationUpdate,
	InitiatingMessage__value_PR_MMEConfigurationUpdate,
	InitiatingMessage__value_PR_WriteReplaceWarningRequest,
	InitiatingMessage__value_PR_HandoverNotify,
	InitiatingMessage__value_PR_E_RABReleaseIndication,
	InitiatingMessage__value_PR_Paging,
	InitiatingMessage__value_PR_DownlinkNASTransport,
	InitiatingMessage__value_PR_InitialUEMessage,
	InitiatingMessage__value_PR_UplinkNASTransport,
	InitiatingMessage__value_PR_ErrorIndication,
	InitiatingMessage__value_PR_NASNonDeliveryIndication,
	InitiatingMessage__value_PR_UEContextReleaseRequest,
	InitiatingMessage__value_PR_DownlinkS1cdma2000tunneling,
	InitiatingMessage__value_PR_UplinkS1cdma2000tunneling,
	InitiatingMessage__value_PR_UECapabilityInfoIndication,
	InitiatingMessage__value_PR_ENBStatusTransfer,
	InitiatingMessage__value_PR_MMEStatusTransfer,
	InitiatingMessage__value_PR_DeactivateTrace,
	InitiatingMessage__value_PR_TraceStart,
	InitiatingMessage__value_PR_TraceFailureIndication,
	InitiatingMessage__value_PR_CellTrafficTrace,
	InitiatingMessage__value_PR_LocationReportingControl,
	InitiatingMessage__value_PR_LocationReportingFailureIndication,
	InitiatingMessage__value_PR_LocationReport,
	InitiatingMessage__value_PR_OverloadStart,
	InitiatingMessage__value_PR_OverloadStop,
	InitiatingMessage__value_PR_ENBDirectInformationTransfer,
	InitiatingMessage__value_PR_MMEDirectInformationTransfer,
	InitiatingMessage__value_PR_ENBConfigurationTransfer,
	InitiatingMessage__value_PR_MMEConfigurationTransfer,
	InitiatingMessage__value_PR_PrivateMessage
} InitiatingMessage__value_PR;

/* InitiatingMessage */
typedef struct InitiatingMessage {
	ProcedureCode_t	 procedureCode;
	Criticality_t	 criticality;
	struct InitiatingMessage__value {
		InitiatingMessage__value_PR present;
		union InitiatingMessage__value_u {
			HandoverRequired_t	 HandoverRequired;
			HandoverRequest_t	 HandoverRequest;
			PathSwitchRequest_t	 PathSwitchRequest;
			E_RABSetupRequest_t	 E_RABSetupRequest;
			E_RABModifyRequest_t	 E_RABModifyRequest;
			E_RABReleaseCommand_t	 E_RABReleaseCommand;
			InitialContextSetupRequest_t	 InitialContextSetupRequest;
			HandoverCancel_t	 HandoverCancel;
			Reset_t	 Reset;
			S1SetupRequest_t	 S1SetupRequest;
			UEContextModificationRequest_t	 UEContextModificationRequest;
			UEContextReleaseCommand_t	 UEContextReleaseCommand;
			ENBConfigurationUpdate_t	 ENBConfigurationUpdate;
			MMEConfigurationUpdate_t	 MMEConfigurationUpdate;
			WriteReplaceWarningRequest_t	 WriteReplaceWarningRequest;
			HandoverNotify_t	 HandoverNotify;
			E_RABReleaseIndication_t	 E_RABReleaseIndication;
			Paging_t	 Paging;
			DownlinkNASTransport_t	 DownlinkNASTransport;
			InitialUEMessage_t	 InitialUEMessage;
			UplinkNASTransport_t	 UplinkNASTransport;
			ErrorIndication_t	 ErrorIndication;
			NASNonDeliveryIndication_t	 NASNonDeliveryIndication;
			UEContextReleaseRequest_t	 UEContextReleaseRequest;
			DownlinkS1cdma2000tunneling_t	 DownlinkS1cdma2000tunneling;
			UplinkS1cdma2000tunneling_t	 UplinkS1cdma2000tunneling;
			UECapabilityInfoIndication_t	 UECapabilityInfoIndication;
			ENBStatusTransfer_t	 ENBStatusTransfer;
			MMEStatusTransfer_t	 MMEStatusTransfer;
			DeactivateTrace_t	 DeactivateTrace;
			TraceStart_t	 TraceStart;
			TraceFailureIndication_t	 TraceFailureIndication;
			CellTrafficTrace_t	 CellTrafficTrace;
			LocationReportingControl_t	 LocationReportingControl;
			LocationReportingFailureIndication_t	 LocationReportingFailureIndication;
			LocationReport_t	 LocationReport;
			OverloadStart_t	 OverloadStart;
			OverloadStop_t	 OverloadStop;
			ENBDirectInformationTransfer_t	 ENBDirectInformationTransfer;
			MMEDirectInformationTransfer_t	 MMEDirectInformationTransfer;
			ENBConfigurationTransfer_t	 ENBConfigurationTransfer;
			MMEConfigurationTransfer_t	 MMEConfigurationTransfer;
			PrivateMessage_t	 PrivateMessage;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiatingMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiatingMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_InitiatingMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_InitiatingMessage_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _InitiatingMessage_H_ */
#include <asn_internal.h>
