/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1/S1AP-IEs.asn"
 * 	`asn1c -no-gen-example -fcompound-names -S skeletons -D asn1c`
 */

#ifndef	_ServedGUMMEIs_H_
#define	_ServedGUMMEIs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ServedGUMMEIsItem;

/* ServedGUMMEIs */
typedef struct ServedGUMMEIs {
	A_SEQUENCE_OF(struct ServedGUMMEIsItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServedGUMMEIs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServedGUMMEIs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ServedGUMMEIsItem.h"

#endif	/* _ServedGUMMEIs_H_ */
#include <asn_internal.h>
